format = """
[ ](bg:#97B676)\
[$directory](bg:#97B676 fg:#22272F)\
[](fg:#97B676 bg:#8FBCBB)\
[$git_branch](bg:#8FBCBB fg:#22272F)\
[$git_status](bg:#8FBCBB fg:#22272F)\
[](fg:#8FBCBB bg:#D79DCC)\
[$lua$conda$c$python$cmake$golang$java$rust$golang](bg:#D79DCC fg:#22272F)\
[](fg:#D79DCC)\
$cmd_duration\
$character\
"""

[directory]
read_only = ''
format = ' $path $read_only '

[character]
success_symbol = '[ \$](bold green)'
error_symbol = '[ ✗](bold red)'

[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[git_branch]
format = ' $symbol$branch'

[git_status]
conflicted = ""
ahead = ""
behind = ""
diverged = ""
modified = ""
untracked = "󰡯"
stashed = "📦"
staged = "✚"
renamed = " "
deleted = "🗑"
format = ' $all_status$ahead_behind '

[conda]
symbol = ' '
format = ' $symbol $environment '

[cmake]
symbol = ' '
format = ' $symbol$version '

[c]
symbol = ' '
format = ' $symbol$version '

[golang]
symbol = ' '
format = ' $symbol$version '

[java]
symbol = ' '
format = ' $symbol$version '

[python]
symbol = ' '
format = ' $symbol$version $virtualenv '

[rust]
format = ' $symbol '

[lua]
symbol = ' '
format = ' $symbol$version '
